project:
  type: website

website:
  title: "hygorxaraujo"
  site-url: https://hygorxaraujo.com/
  description: My personal blog
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-FBHJ31L8R4"
    version: 4
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: sandstone
      dark: solar
    css: styles.css
    toc: true
    code-line-numbers: true
execute:
  enabled: true