project:
  type: website
  resources:
    - "assets/"
  render:
    - "posts/"
    - "index.qmd"
    - "about.qmd"
    - "!templates/"
    - "!docs/"

website:
  title: "hygorxaraujo"
  description: My personal blog
  site-url: "https://hygorxaraujo.com/"
  favicon: assets/favicon.ico
  repo-url: "https://github.com/hygorxaraujo/personalsite"
  repo-branch: "gh-pages"
  issue-url: "https://github.com/hygorxaraujo/personalsite/issues"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph:
    image: assets/profile.jpg
    locale: en_US
    site-name: "Hygor X. Araújo"
  twitter-card:
    image: assets/profile.jpg
  cookie-consent:
    type: express
  google-analytics:
    tracking-id: "G-FBHJ31L8R4"
    version: 4
  navbar:
    logo: assets/profile.jpg
    title: "Hygor X. Araújo"
    left:
      - text: Writing
        href: index.html
    right:
      - about.qmd
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: [zephyr, custom.scss]
      dark: [darkly, custom-dark.scss, custom.scss]
    toc: true
    code-line-numbers: true
    mermaid:
      theme: neutral

execute:
  enabled: true
  freeze: true
