project:
  type: website
  resources:
    - "assets/"
  render:
    - "posts/"
    - "index.qmd"
    - "about.qmd"
    - "!templates/"

website:
  title: "hygorxaraujo"
  description: My personal blog
  site-url: "https://hygorxaraujo.com/"
  repo-url: "https://github.com/hygorxaraujo/personalsite"
  repo-branch: "gh-pages"
  issue-url: "https://github.com/hygorxaraujo/personalsite/issues"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  open-graph: true
  cookie-consent:
    type: express
  google-analytics:
    tracking-id: "G-FBHJ31L8R4"
    version: 4
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: [zephyr, custom.scss]
      dark: [darkly, custom.scss]
    toc: true
    code-line-numbers: true
    mermaid:
      theme: dark

execute:
  enabled: true
