[project]
name = "personalsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyterlab>=4.4.8",
    "jupyterlab-quarto>=0.3.5",
    "matplotlib>=3.10.1",
    "nvidia-cudnn-cu12==9.3.0.75",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "seaborn>=0.13.2",
    "tensorflow[and-cuda]>=2.19.0",
]

[dependency-groups]
dev = [
    "personalsite",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.13",
]

[tool.setuptools.packages]
find = {namespaces = false}

[tool.uv]
package = true

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
personalsite = { workspace = true }

[project.scripts]
create-posts = "scripts.create_posts:main"
